apiVersion: v1
data:
  ClusterConfiguration: |
    apiServer:
      extraArgs:
        authorization-mode: Node,RBAC
        bind-address: 0.0.0.0
      timeoutForControlPlane: 4m0s
    apiVersion: kubeadm.k8s.io/v1beta3
    certificatesDir: /etc/kubernetes/pki
    clusterName: kubernetes
    controlPlaneEndpoint: 147.28.141.217:6443
    controllerManager:
      extraArgs:
        bind-address: 10.65.8.131
    dns: {}
    etcd:
      local:
        dataDir: /var/lib/etcd
    imageRepository: k8s.gcr.io
    kind: ClusterConfiguration
    kubernetesVersion: v1.23.3
    networking:
      dnsDomain: cluster.local
      serviceSubnet: 10.96.0.0/12
    scheduler:
      extraArgs:
        bind-address: 10.65.8.131
kind: ConfigMap
metadata:
  creationTimestamp: "2022-08-09T13:15:00Z"
  name: kubeadm-config
  namespace: kube-system
  resourceVersion: "196"
  uid: 33449dbd-0aaa-45e7-bc05-7341fb82a82f
