#!/bin/sh

(sleep 2 && sed -e 's/nondefault/default/' /etc/kubernetes/kube-scheduler.conf) &

mv /usr/bin/kube-scheduler /usr/local/bin/kube-scheduler

exec -a "/usr/local/bin/kube-scheduler" /usr/local/bin/kube-scheduler --config /etc/kubernetes/kube-scheduler.conf "$@"
